apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring_deployment
  template:
    metadana:
      labels:
        app: spring_deployment
    spec:
      containers:
        - name: spring_app
          image: muszeczka/spring_demo:latest
---
apiVersion: apps/v1
kind: Service
metadata:
  name: spring_service
spec:
  selector:
    app: spring_service
  ports:
    -protocol: TCP
     port: 80
     targetPort: 5432
