apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-deployment
  template:
    metadata:
      labels:
        app: spring-deployment
    spec:
      containers:
        - name: spring-app
          image: muszeczka/spring_demo:latest
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
